<a href="https://colab.research.google.com/github/BushraOnika/Pytorch_learn/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
if torch.cuda.is_available():
    print("CUDA is available.")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("CUDA is not available.")

CUDA is not available.


## Creating a Tensor

In [3]:
 # using empty
 a = torch.empty(2,3)
 a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
type(a)

torch.Tensor

In [5]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
#using rand gives random values every time
torch.rand(2,3)

tensor([[0.3773, 0.5477, 0.1144],
        [0.3301, 0.4332, 0.2034]])

In [8]:
# using seeds we got random values but every time same random values
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])


tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
#other ways

# arrange
print("using arrange", torch.arange(0,10))
print("using arrange", torch.arange(0,10,2))

# linespace evenly space (linear space)
print("using linespace: ", torch.linspace(0,10,10))

# identity matrix (eye)
print("Usinh eye:", torch.eye(5))

#using full
print("using full: " ,torch.full((2,3),5))

using arrange tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using arrange tensor([0, 2, 4, 6, 8])
using linespace:  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Usinh eye: tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full:  tensor([[5, 5, 5],
        [5, 5, 5]])


## Tensor Shape

In [12]:
x= torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
x.shape

torch.Size([2, 3])

In [14]:
torch.empty_like(x)

tensor([[ 0,  0,  0],
        [ 0,  0, 81]])

In [15]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
torch.rand_like(x)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [24]:
torch.rand_like(x,dtype=torch.float64)

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)

## Tensor Data Type

In [19]:
x.dtype

torch.int64

In [21]:
# assing datatype
torch.tensor([1,2,3,4,5],dtype=torch.float64)

tensor([1., 2., 3., 4., 5.], dtype=torch.float64)

In [22]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# MAthematics Operations

## scalar operation


In [25]:
x = torch.rand(2,2)
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [26]:
#addition
x + 2

# substraction
x - 2

#multiplication
x * 5

# division
x/2

# int division
(x*100)//3

# mod
(x*100)//3%2

#power
x**2

tensor([[0.0501, 0.0914],
        [0.0318, 0.6787]])

In [27]:
c = torch.tensor([1, -2, 3, -4])

In [28]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [29]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
# round
torch.round(d)

In [ ]:
 # ceil
torch.ceil(d)

In [ ]:
# floor
torch.floor(d)

In [ ]:
# camp arange tensor
torch.clamp(d,min=1,max=3)

## Reduction Operation

In [30]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[4., 6., 0.],
        [1., 9., 9.]])

In [31]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([10., 19.])

In [32]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([2.5000, 7.5000, 4.5000])

In [33]:
 #median
torch.median(e)

tensor(4.)

In [34]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [35]:
# product
torch.prod(e)

tensor(0.)

In [36]:
# standard deviation
torch.std(e)

tensor(3.8687)

In [37]:
# variance
torch.var(e)

tensor(14.9667)

In [38]:
# argmax
torch.argmax(e)

tensor(4)

In [39]:
# argmin
torch.argmin(e)

tensor(2)

## 4. Matrix operations

In [40]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[8, 0, 7],
        [0, 0, 9]])
tensor([[5, 7],
        [3, 9],
        [4, 0]])


In [41]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[68, 56],
        [36,  0]])

In [42]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [43]:
# transpose
torch.transpose(f, 0, 1)

tensor([[8, 0],
        [0, 0],
        [7, 9]])

In [44]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 7., 5.],
        [9., 9., 7.],
        [5., 9., 8.]])

In [45]:
# determinant
torch.det(h)

tensor(-34.0000)

In [46]:
# inverse
torch.inverse(h)

tensor([[-0.2647,  0.3235, -0.1176],
        [ 1.0882, -0.4412, -0.2941],
        [-1.0588,  0.2941,  0.5294]])

## Comparison

In [47]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[9, 7, 9],
        [2, 6, 7]])
tensor([[7, 8, 3],
        [6, 1, 5]])


In [48]:
i>j

tensor([[ True, False,  True],
        [False,  True,  True]])

In [49]:
i<j

tensor([[False,  True, False],
        [ True, False, False]])

In [50]:
i==j

tensor([[False, False, False],
        [False, False, False]])

In [51]:
i !=j

tensor([[True, True, True],
        [True, True, True]])

## special functions

In [52]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[5., 0., 4.],
        [3., 8., 8.]])

In [53]:
# log
torch.log(k)

tensor([[1.6094,   -inf, 1.3863],
        [1.0986, 2.0794, 2.0794]])

In [54]:
# exp
torch.exp(k)

tensor([[1.4841e+02, 1.0000e+00, 5.4598e+01],
        [2.0086e+01, 2.9810e+03, 2.9810e+03]])

In [56]:
# sqrt
torch.sqrt(k)

tensor([[2.2361, 0.0000, 2.0000],
        [1.7321, 2.8284, 2.8284]])

In [57]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.5000, 0.9820],
        [0.9526, 0.9997, 0.9997]])

In [58]:
# softmax
torch.softmax(k, dim=0)

tensor([[8.8080e-01, 3.3535e-04, 1.7986e-02],
        [1.1920e-01, 9.9966e-01, 9.8201e-01]])

In [60]:
# relu
torch.relu(k)

tensor([[5., 0., 4.],
        [3., 8., 8.]])

## Inplace Operations

In [61]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6179, 0.3379, 0.2170],
        [0.9454, 0.7116, 0.1157]])
tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])


In [62]:
m.add_(n)

tensor([[1.2752, 0.6830, 0.2624],
        [1.9251, 1.2663, 0.8025]])

In [63]:
m

tensor([[1.2752, 0.6830, 0.2624],
        [1.9251, 1.2663, 0.8025]])

In [64]:
n

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [65]:
torch.relu(m)

tensor([[1.2752, 0.6830, 0.2624],
        [1.9251, 1.2663, 0.8025]])

In [66]:
m.relu_()

tensor([[1.2752, 0.6830, 0.2624],
        [1.9251, 1.2663, 0.8025]])

In [67]:
m

tensor([[1.2752, 0.6830, 0.2624],
        [1.9251, 1.2663, 0.8025]])

## Copying a Tensor




In [68]:
a = torch.rand(2,3)
a

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [71]:
b = a.clone()

In [72]:
id(a)

138359503021136

In [73]:
id(b)

138359503020176

# Numpy and Pytorch

In [84]:
import numpy as np

In [77]:
a=torch.tensor([1,2,3,3])
a

tensor([1, 2, 3, 3])

In [80]:
b=a.numpy()
b

array([1, 2, 3, 3])

In [81]:
type(a)

torch.Tensor

In [82]:
type(b)

numpy.ndarray

In [86]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [87]:
d=torch.from_numpy(c)
d

tensor([1, 2, 3])