<a href="https://colab.research.google.com/github/BushraOnika/Pytorch_learn/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
if torch.cuda.is_available():
    print("CUDA is available.")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("CUDA is not available.")

CUDA is not available.


## Creating a Tensor

In [5]:
 # using empty
 a = torch.empty(2,3)
 a

tensor([[1.7638e-20, 0.0000e+00, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 4.3746e-41]])

In [6]:
type(a)

torch.Tensor

In [7]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
#using rand gives random values every time
torch.rand(2,3)

tensor([[0.6436, 0.3712, 0.4858],
        [0.3950, 0.4152, 0.3998]])

In [10]:
# using seeds we got random values but every time same random values
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)